import { Document, Page, View, Text, Image, StyleSheet, renderToFile } from '@react-pdf/renderer';
import path from 'path';
import { UPLOADS_DIR } from './db';

const logoPath = path.resolve(process.cwd(), 'public/icons/icon-192x192.png');

const styles = StyleSheet.create({
  page: { padding: 32, backgroundColor: '#0b1120', color: '#f8fafc', fontFamily: 'Helvetica' },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 24, borderBottomWidth: 2, borderBottomColor: '#3b82f6', paddingBottom: 16 },
  logo: { width: 120, height: 40, objectFit: 'contain' },
  title: { fontSize: 18, fontWeight: 'bold', marginLeft: 'auto', color: '#f8fafc' },
  columns: { flexDirection: 'row', gap: 24 },
  left: { flex: 1.5 },
  right: { flex: 1 },
  label: { fontSize: 10, color: '#94a3b8', marginBottom: 4 },
  value: { fontSize: 15, color: '#f8fafc', marginBottom: 12 },
  amount: { fontSize: 26, color: '#3b82f6', fontWeight: 'bold', marginBottom: 12 },
  meta: { fontSize: 10, color: '#64748b', marginTop: 24 },
  receipt: { width: '100%' },
});

export type PdfInput = {
  company_name: string;
  app_name: string;
  category_name: string;
  amount: number;
  date: string;
  vendor: string;
  notes: string;
  odometer: number | null;
  receipt_image: string;
};

function ReceiptDoc({ data }: { data: PdfInput }) {
  const receiptPath = path.join(UPLOADS_DIR, data.receipt_image);
  return (
    <Document title={`Expense Receipt - ${data.category_name} - ${data.date}`}>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Image src={logoPath} style={styles.logo} />
          <Text style={styles.title}>Expense Receipt</Text>
        </View>

        <View style={styles.columns}>
          <View style={styles.left}>
            <Text style={styles.label}>Company</Text>
            <Text style={styles.value}>{data.company_name || data.app_name}</Text>

            <Text style={styles.label}>Category</Text>
            <Text style={styles.value}>{data.category_name}</Text>

            <Text style={styles.label}>Amount</Text>
            <Text style={styles.amount}>${data.amount.toFixed(2)}</Text>

            <Text style={styles.label}>Date</Text>
            <Text style={styles.value}>{data.date}</Text>

            <Text style={styles.label}>Vendor / Merchant</Text>
            <Text style={styles.value}>{data.vendor}</Text>

            {data.odometer != null && data.odometer !== 0 && (
              <>
                <Text style={styles.label}>Odometer</Text>
                <Text style={styles.value}>{data.odometer.toLocaleString()} miles</Text>
              </>
            )}

            <Text style={styles.label}>Notes</Text>
            <Text style={styles.value}>{data.notes || '-'}</Text>

            <Text style={styles.meta}>
              Generated by {data.app_name} on {new Date().toLocaleDateString()}
            </Text>
          </View>

          <View style={styles.right}>
            <Image src={receiptPath} style={styles.receipt} />
          </View>
        </View>
      </Page>
    </Document>
  );
}

export async function generateReceiptPdf(data: PdfInput, outputPath: string) {
  const doc = <ReceiptDoc data={data} />;
  await renderToFile(doc, outputPath);
}
